sudo: "required"
dist: "trusty"
language: "python"
python: "3.5"
cache: "pip"
before_install:
  # Installing Czech LOCALE - https://docs.travis-ci.com/user/common-build-problems/#System%3A-Required-language-pack-isn%E2%80%99t-installed
  - sudo apt-get update
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-cs
script:
  - "blog lint"
env:
  global:
    - secure: "UAG7Tk6EbqFNKfzNsEAnnQbNBPFF7tO1Nu25yhByIEYO4Qi2eaHQuHg8nthaamiKplw1MouEGpFFhwXWzthW3xJ4m3CKJsJCxjcKtmsirgTxKoJv8SpbNNMHkEBMYYjhYnfEiD67G5PEKl8ekJMnHhH+5Qn9tgerKNibWZIDvLU="
deploy:
  provider: "script"
  script: "blog deploy"
  on:
    branch: "master"
    repo: "honzajavorek/honzajavorek.cz"
