language: python
python:
    - "3.5"
install:
    - "make install"
script:
    - "make lint"
deploy:
    provider: "script"
    script: "make deploy"
    on:
        branch: "master"
        python: "3.4"
        repo: "honzajavorek/honzajavorek.cz"
sudo: false
