language: python
python:
    - "3.4"
env:
    global:
        - secure: "eQaNOSWB9XQeiAeS5qhVvdTOikbN8ITYGsugN3LM4lNkANauM9yf7Rb5TWwExgm9nwtTDuCLeEkSMj8Dey/GWUOp06adqoiMM23QfsMtepVQN6GMS+qLmZNCbznzg0svKYv8zFQ/aKprNU1QyvRZJJdyfnOnfG+KpdZRP3ShOXU="
install:
    - "make install"
script:
    - "make test"
deploy:
    provider: "script"
    script: "make deploy"
    on:
        branch: "master"
        python: "3.4"
        repo: "honzajavorek/honzajavorek.cz"
