language: "python"
python: "3.6"
cache: "pip"
addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-cs
script:
  - "blog lint"
env:
  global:
    - secure: "Hie2d1kHFDosres0dt+ZUfK57BOmzJrW8J9+bP0kemBGvV4v+NLdLEtjeMNg/fcq6mO2g1a6M7K02N5hYm3bv0MhN2u2j5afQmQhqgJG1FcPhMR4YFzQ3WqEHMXU09DGu56Pe7PJ5WiKa2PAMUnmDkocbsaZ4cBrT51y4IZOj2M="
deploy:
  provider: "script"
  script: "blog deploy"
  on:
    branch: "master"
    repo: "honzajavorek/honzajavorek.cz"
