version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python -m pip install pip pipenv --upgrade
            sudo npm install npm@6 --global
            ./install.sh

      - run:
          name: run tests
          command: |
            ./lint.sh

      - deploy:
          environment:
            TRAVIS: true
            TRAVIS_REPO_SLUG: honzajavorek/honzajavorek.cz
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo pip install ghp-import
              ./deploy.sh
            fi
