version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.7-node

jobs:
  test:
    <<: *defaults
    steps:
      - "checkout"
      - run:
          name: Installing dependencies
          command: |
            python -m pip install pip pipenv --upgrade
            sudo npm install npm@6 --global
            ./install.sh
      - run:
          name: "Running tests"
          command: "./lint.sh"
  deploy:
    <<: *defaults
    steps:
      - "checkout"
      - run:
          name: Installing dependencies
          command: |
            python -m pip install pip pipenv --upgrade
            sudo npm install npm@6 --global
            ./install.sh
      - deploy:
          environment:
            TRAVIS: true
            TRAVIS_REPO_SLUG: "honzajavorek/honzajavorek.cz"
          command: |
            sudo pip install ghp-import
            ./deploy.sh

workflows:
    version: 2
    test-deploy:
      jobs:
        - test
        - deploy:
            requires:
              - test
            filters:
              branches:
                only: "master"
    nightly:
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only: "master"
      jobs:
        - test
        - deploy:
            requires:
              - test
