name: deploy

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: amondnet/now-deployment@v2
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-args: '--prod'
          now-org-id: ${{ secrets.NOW_ORG_ID }}
          now-project-id: ${{ secrets.NOW_PROJECT_ID }}
